
= gmail-exporter
Davide Cavestro <https://github.com/davidecavestro[@davidecavestro]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URIs:
:uri-repo: https://github.com/davidecavestro/gmail-exporter
:uri-issues: {uri-repo}/issues
:uri-search-issues: {uri-repo}/search?type=Issues
:uri-ci-travis: https://travis-ci.org/davidecavestro/gmail-exporter
:uri-coverage-coveralls: https://coveralls.io/github/davidecavestro/gmail-exporter?branch=main
ifdef::status[]
image:https://img.shields.io/github/license/davidecavestro/gmail-exporter.svg[MIT License, link=#copyright-and-license]
image:https://img.shields.io/github/languages/code-size/badges/shields.svg[GitHub code size in bytes]


image:https://img.shields.io/github/release/davidecavestro/gmail-exporter.svg[GitHub release]
image:https://img.shields.io/github/commits-since/davidecavestro/gmail-exporter/latest.svg[Github commits (since latest release)]

endif::[]

Export you gmail messages from command line

toc::[]

:imagesdir: docs/images
:icons: font

Gmail-exporter is a command line utility for exporting a local copy of email messages and related attachments from your Gmail account.


# Features

- Export email messages to a spreadsheet
- Optionally export related attachments and put refs into the spreadsheet
- Filter by label exported messages
- Command line interface with optional progress status for long tasks

For more info please see the link:docs/index.adoc[documentation].


# Prerequisites

The user should save her own (access credentials)[https://developers.google.com/workspace/guides/create-credentials#desktop-app] as a local file (_credentials.json_ by default) with contents similar to the following snippet:
```
{
  "installed": {
    "client_id": "...",
    "project_id": "gmail-exporter-343907",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "...",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}

```

If the token file (_token.json_ by default) exists, it should stores the user's access and refresh tokens as follows.
```
{
  "access_token": "...",
  "token_type": "Bearer",
  "refresh_token": "...",
  "expiry": "2022-07-17T13:30:07.560873398+02:00"
}
```
If it doesn't exist or doesn't contain a valid token, it is created and filled automatically when the authorization flow completes for the first time, that is when the user consent access. 


# Usage

Invoke the `gmail-exporter` executable passing appropriate options.

## Quickstarts

Export all messages from the trashcan
`./gmail-exporter export TRASH`


### Fine-tune paging

Messages are downloaded in blocks (pages): set the size of each block to max 50 messages
`gmail-exporter --page-size 50 TRASH`

Read at max 200 pages of messages
`gmail-exporter --pages-limit 200 TRASH`


### Throttling

Limit the transfer of messages at 1 per second
`gmail-exporter --messages-per-sec 1 TRASH`

Limit the download of attachments at 5 per second
`gmail-exporter --attachments-per-sec 5 TRASH`

### Batch mode

Prevent both opening the browser window for auth and eventually writing the obtained token
`gmail-exporter --batch TRASH`


## Authentication

When the application launches, it requests that the user grant access to data in the relevant Google account.

If the user consents, the application requests and receives a temporary token to access Gmail
data. All the exchanged data is just kept within the user local system.
The temporary token is long-lived and saved into your local folder (by default within file _token.json_).
When expired, it is automatically refreshed.


# How to build

Clone the project and run
`go build`
