
= gmail-exporter
Davide Cavestro <https://github.com/davidecavestro[@davidecavestro]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: main
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URIs:
:uri-repo: https://github.com/davidecavestro/gmail-exporter
:uri-issues: {uri-repo}/issues
:uri-search-issues: {uri-repo}/search?type=Issues
// :url-rel-file-base: {url-repo}/blob/HEAD/
:url-rel-file-base: link:
:url-license: {url-rel-file-base}LICENSE
// images:
image:https://img.shields.io/github/license/badges/shields.svg[MIT License, link=#copyright-and-license]
image:https://img.shields.io/github/languages/code-size/badges/shields.svg[GitHub code size in bytes]
image:https://img.shields.io/github/release/davidecavestro/gmail-exporter.svg[GitHub release]
image:https://img.shields.io/github/commits-since/davidecavestro/gmail-exporter/latest.svg[Github commits (since latest release)]


:imagesdir: docs/images
:icons: font

{uri-repo}[Gmail-exporter] is a command line utility for exporting a local copy of email messages and related attachments from your Gmail account.

image::export_session.svg[Example for exporting messages tagged as FOOBAR, then checking exported contents]

toc::[]

== Features

- Export email messages to a spreadsheet
- Optionally export related attachments and put refs into the spreadsheet
- Filter by label exported messages
- Command line interface with optional progress status for long tasks


== Privacy policy

_Gmail-exporter_'s use of information received from Google APIs will adhere to https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes[Google API Services User Data Policy], including the Limited Use requirements.

== Prerequisites

The user should generate and save the https://developers.google.com/workspace/guides/create-credentials#desktop-app[access credentials] as a local file (i.e. _credentials.json_). +
See xref:credentials-json[credentials.json] for further details.

.Optional authentication persistence
[NOTE]
====
*token.json* file

If the token file (_token.json_ by default) exists, it should store the user's access and refresh tokens.

If it doesn't exist or doesn't contain a valid token, it is created and filled automatically when the authorization flow completes for the first time, that is when the user consent access. +
See xref:token-json[token.json] for further details.

====

== Usage

Invoke the `gmail-exporter` executable passing appropriate options.


=== Quickstarts

This paragraph shows some usage examples. +
Use `./gmail-exporter help` to get the full list of available options.

==== Export sent messages from the trashcan

`./gmail-exporter export SENT`

==== List available labels

`./gmail-exporter labels`

==== Fine-tune paging

Messages are downloaded in blocks (pages): set the size of each block to max 50 messages +
`gmail-exporter --page-size 50 TRASH`

Read at max 200 pages of messages +
`gmail-exporter --pages-limit 200 TRASH`


==== Throttling

Limit the transfer of messages at 1 per second +
`gmail-exporter --messages-per-sec 1 TRASH`

Limit the download of attachments at 5 per second +
`gmail-exporter --attachments-per-sec 5 TRASH`


==== Batch mode

Prevent both opening the browser window for auth and eventually writing the obtained token
`gmail-exporter --batch TRASH`


=== Authentication

When the application launches, it requests that the user grant access to data in the relevant Google account.

If the user consents, the application requests and receives a temporary token to access Gmail
data. All the exchanged data is just kept within the user local system.

The temporary token is long-lived and saved into your local folder (by default within file _token.json_). +
When expired, it is automatically refreshed.

[[credentials-json]]The credentials file should be structured as follows 

.credentials.json
[source,json]
----
{
  "installed": {
    "client_id": "...",
    "project_id": "gmail-exporter-343907",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "...",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}
----

[[token-json]]The auth token file should be structured as follows

.token.json
[source,json]
----
{
  "access_token": "...",
  "token_type": "Bearer",
  "refresh_token": "...",
  "expiry": "2022-07-17T13:30:07.560873398+02:00"
}
----


== How to build

Clone the project and run +
`go build`

== How to release

Add a tag with proper message and push it
```
git tag v0.0.1 -m "First public release for wider testing."
git push origin v0.0.1 
```

== Copyright and License

Copyright (C) 2022-present Davide Cavestro.
Use of this software is granted under the terms of the MIT License.

See the {url-license}[LICENSE] for the full license text.